#!/bin/bash
# build-project --- Build the project from sources.
set -e
export TOOLS_DIR="$(unset CDPATH; cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
source $TOOLS_DIR/use

cd $PROJ_DIR

rm -rf lib

echo "Linting sources ..."
tslint --format=verbose src/*.ts

echo "Compiling TypeScript files ..."
tsc --jsx react

echo -e "\nBundling javascript ..."
browserify lib/index.js --debug --outfile app/app.js
